name: Check proofs with Coq
on:
  pull_request: {}
permissions: read-all

jobs:
  coq:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: nicknovitski/nix-develop@v1
    - run: make -C ladr
